### ISSUE TITLE
Abnormal results of interaction model

### ISSUE THREAD

**Issue by yrjia1015** [broadinstitute/tensorqtl#121]
Hi.  
I am using tensorqtl to perform interaction  cis-QTL mapping. I believe that the interaction model simply adds interaction terms. Even if the interactions are different, the snp-gene pairs tested in eQTL mapping should be the same, only the p-values and beta values may change. However, in my results, the number of snp-gene pairs tested in the eQTL results with different interaction terms (in different cells) is not equal.
Is this situation normal?

Thanks

**Comment by francois-a** [comment]
Yes that's expected — to avoid artifacts due to outlier effects, a MAF filter that depends on the interaction term is applied (i.e., variants with MAF ≥ 0.05 in the samples belonging to each of the top and bottom halves of the interaction term). This can be adjusted with `--maf_threshold_interaction`. Please see section "Identification of cell type interaction eQTLs and sQTLs" in the supplement of https://www.science.org/doi/10.1126/science.aaz8528 for additional details.

**Comment by yrjia1015** [comment]
Thank you for your reply. Under the same phenotype and genotype background, changing only the cell score covariate of the interaction term can also lead to differences in the overall SNP gene pair of the test.

Can I understand that when testing each gene, only variations belonging to the upper and lower parts of the cell score distribution were considered, and the frequency of secondary alleles for these variations was not less than 5%?

This phenomenon is not caused by operational errors.
