### ISSUE TITLE
sQTL cis mod output file only one cluster per gene

### ISSUE THREAD

**Issue by zhangpicb** [broadinstitute/tensorqtl#161]
Dear @francois-a 

Most gene have more than one cluster,why cis mod output file only one cluster per gene?

Thanks in advanced!

**Comment by francois-a** [comment]
This is by design, only the top association is returned in the output of map_cis (since all clusters corresponding to a gene are tested jointly). To get all significant associations, you can run [post.get_significant_pairs](https://github.com/broadinstitute/tensorqtl/blob/master/tensorqtl/post.py#L299). See also [here](https://github.com/broadinstitute/tensorqtl/issues/151).

**Comment by zhangpicb** [comment]
Thanks for quick reply!

Permutation mode for sQTL,qvalue is adjusted for per gene,not for per gene's clusters.
Is my understanding correct?

Thanks in advanced!

**Comment by francois-a** [comment]
Yes, everything is at the gene level.
