### ISSUE TITLE
Beta-value for trans-eQTL

### ISSUE THREAD

**Issue by xtmgah** [broadinstitute/tensorqtl#17]
Hello, Quick question, for trans-eQTL, how to output the Beta value? The out put only output p-value and maf. thanks.

**Comment by francois-a** [comment]
Hi,
Thanks for pointing this out. This has been on the to-do list for a while. Added in 1ba37bb876b9dddd26d58c3070431265ece42a8f; the output (when `return_sparse = True`) now includes `b` and `b_se`.

**Comment by JonMarten** [comment]
Hi Francois, I updated to the github version of tensorQTL and ran this. While it does output betas it also seems to have changed the p-value output, they're now all much larger. Is this an intended consequence?

**Comment by JonMarten** [comment]
Hi Francois, thanks for adding this.

I've noticed that as well as betas, the p-values have changed. 

Using the same script each time, tensorqtl obtained through `pip install tensorqtl`, reports 8 SNPs as significant, but the version from `pip install git+https://github.com/broadinstitute/tensorqtl.git#egg=tensorqtl` gives no SNPs as significant. All other parameters and input data are identical. (It also runs a lot faster!)

Has the calculation of p-values changed?

**Comment by francois-a** [comment]
Hi,
Can you please provide specific data to reproduce the issues you're reporting?

The p-value calculation has not changed, and the output should be identical between versions. It's also unclear why you're seeing speed differences. I just re-tested these versions using the GEUVADIS example and am getting close to identical runtimes.

The only change in the latest commit is the addition of an imputation step for missing values at https://github.com/broadinstitute/tensorqtl/commit/1ba37bb876b9dddd26d58c3070431265ece42a8f#diff-c20eed07a12120ef8f33386bed4c6603R101. I added this for consistency with the cis-QTL code. This would change the p-values for variants with missing values, but such variants should generally be excluded from trans-QTL mapping (before running tensorQTL) due to the higher risk of being artifacts.

**Comment by JonMarten** [comment]
Thanks - I wonder if that could be it, I'll check. I have the usual data protection problems but if it's not being driven by missingness I'll try and recreate with toy or randomised data and share here.

As for the speed, if it's nothing you've changed, I strongly suspect it's just our cluster's quirky file system.

**Comment by JonMarten** [comment]
So I've checked by manually setting missing SNPs to different values and this imputation is definitely what's driving the effect I'm observing. Thanks!

**Comment by francois-a** [comment]
Great, thanks for confirming. I recommend filtering those out for trans-QTL mapping.
