### ISSUE TITLE
Understand about the output of interactionQTL

### ISSUE THREAD

**Issue by shengxin321** [broadinstitute/tensorqtl#18]
Hi,
   Can any one help me understand, what is the meaning of each column of interaction QTL output,
b_g	b_g_se	pval_i	b_i	b_i_se	pval_gi	b_gi	b_gi_se

b_g is beta of SNP?
b_g_se is SE of SNP?
pval_i is the pvalue of the interaction trait? so no value of SNP (genotype)?
b_i is beta of interaction trait?
p_gi is the Pvlaue of the interaction item?
And how did you define cis-eQTL in this software, is the default 1Mb up- and down-stream of the TSS position?
The tutorial really need to be updated, since this software looks very useful and very fast.
Xin

**Comment by francois-a** [comment]
Hi,

Yes, that's the correct interpretation of these terms. Please see the [README](https://github.com/broadinstitute/tensorqtl/blob/master/README.md) for additional details. The default cis-window is indeed TSS ± 1Mb; you can see the default options when running `python3 -m tensorqtl --help`.

**Comment by jackhump** [comment]
Dear Francois,

Could you give a little more detail on how you recommend correcting interaction QTLs for multiple testing? I've generated cell-type interaction QTL results using some deconvolution estimates (from MuSiC) that I residualised against batch, age, sex, and technical covariates in my RNA-seq data. However, every gene's P-value for the `pval_gi` term in the `_top_assoc.txt.gz` file seems to be significant after either Benjamini-Hochberg or qvalue correction (adjusted P < 0.05). Apologies if I'm misunderstanding something here.

**Comment by francois-a** [comment]
Hi,

Sure -- please see the added information in the [README](https://github.com/broadinstitute/tensorqtl/blob/master/README.md). I just realized that eigenMT was not run by default when running tensorQTL from the CLI. The latest commit fixes that. Otherwise, if importing tensorQTL as module, make sure to use the option `run_eigenmt=True` in `map_nominal`. You should then see the proper adjusted p-values in the column `pval_adj_bh`.

**Comment by shengxin321** [comment]
But the README file has very few things about the interactionQTL.
