### ISSUE TITLE
Incorrect calculation of TSS

### ISSUE THREAD

**Issue by iamjli** [broadinstitute/tensorqtl#37]
It appears that the "TES" is being assigned as the TSS: 

https://github.com/broadinstitute/tensorqtl/blob/897d29cff363527b47041b1b12868115096c8e69/tensorqtl/core.py#L300

though even changing `end` to `start` wouldn't quite fix the issue since genes may be on the reverse strand. Perhaps there should be an option to include strand information in the phenotype files.

**Comment by francois-a** [comment]
Hi, the calculation isn't incorrect. The reason `end` is used is because BED coordinates are 0-indexed, whereas VCF positions are 1-indexed. The BED file needs to specify the center of the cis-window, with `end == start + 1`. The strandedness of a gene needs to be taken account when generating the BED file -- see, for example https://github.com/broadinstitute/pyqtl/blob/master/qtl/io.py#L66.

**Comment by iamjli** [comment]
gotcha, thanks for the clarification!
