### ISSUE TITLE
Error about rank value in cis_independent model

### ISSUE THREAD

**Issue by JFF1594032292** [broadinstitute/tensorqtl#58]
Hi,
I have used tensorqtl cis-independent model to find the independent signal for eQTL. Generally, it works fine, but I'm confusing about some results like this:
![image](https://user-images.githubusercontent.com/49577864/163698911-909468ac-6e33-4d53-9dce-a74e3db2a231.png)
This gene have 7 signals, but it only showed 2 independent variants. I also checked the log file, it seems like it only have 2 independent signals in deed.
![image](https://user-images.githubusercontent.com/49577864/163698867-21c778df-ebf7-498e-813a-a354bd96c9dc.png)
I wonder if there are some errors in the rank values. Similar results also happened on some other genes with 3 or 4 independent signals.

Thanks,
Jiang

**Comment by francois-a** [comment]
Hi, this happens when the forward pass of the stepwise regression identifies signals that are removed during the [backward pass](https://github.com/broadinstitute/tensorqtl/blob/master/tensorqtl/cis.py#L830); the rank of the forward pass variants is kept to indicate that this occurred. This should only be the case for a minority of phenotypes.

**Comment by JFF1594032292** [comment]
Thanks for your quick reply!

**Comment by silvewheat** [comment]
Hello, I have also encountered the same situation. I would like to ask if in this case, should I update the rank values by myself? For example, change 1 and 7 above to 1 and 2?
