### ISSUE TITLE
Regression with phenotype containing 4 expressed genes

### ISSUE THREAD

**Issue by Junjun-Xu** [broadinstitute/tensorqtl#90]
I have two questions.
1. I want to regress with a part of the genotype, so I reduced the genotype file and kept only 4 genes. The result can be run in CPU mode, but an error will be reported when using GPU. The error message is as follows:
![image](https://user-images.githubusercontent.com/33317454/235039221-823dcad3-1f4c-4247-8c3a-3bb4b02fa1ca.png)
Why is this?
2. And I found that using different numbers of genotype files, the calculated q value is different for the same gene. Why?
I will be very very grateful if I can receive your reply.

**Comment by francois-a** [comment]
The first error is because there are too few phenotypes to run qvalue on. Depending on your dataset (you'll need to use more phenotypes in any case), you may want to fix the lambda value used for the pi0 calculation (`--qvalue_lambda` option).

FDR will change if you test a different number of genes, so this is expected.

**Comment by Junjun-Xu** [comment]
Thanks very much for your reply.
Here, I want to know if I only use some genes for testing, such as 30 genes, is this reasonable? Should I adjust or fix the lambda value? Will this have an impact on my results?

**Comment by francois-a** [comment]
For testing purposes you can set `qvalue_lambda` to 0.5 for example, but with only 30 genes the pi0 calculation will be unstable. If your full dataset only includes a small number of phenotypes, separately applying a different FDR procedure will be more appropriate.
